### ISSUE TITLE
Demonstrate data source conversion issues

### ISSUE THREAD

**Issue by ming123456789** [bernhard-42/three-cad-viewer#16] opened 2024-03-08 03:47 UTC
Could you please tell me how to convert the dwg file into the js file in your example?

**Comment by bernhard-42** [comment] 2024-03-08 07:30
Currently this cad viewer is used by https://github.com/bernhard-42/vscode-ocp-cad-viewer and relies on cadquery or build123d code CAD libraries to build 3d objects.
the js format is being created with https://github.com/bernhard-42/ocp-tessellate
You could try cadquery or build123d to import your file and then create the js representation

**Comment by bernhard-42** [comment] 2024-10-19 15:42
closing as duplicate of https://github.com/bernhard-42/three-cad-viewer/issues/17

**Closed by bernhard-42** 2024-10-19 15:42 UTC
Labels: duplicate, question
