### ISSUE TITLE
transfer custom cad

### ISSUE THREAD

**Issue by zhouxinlun** [bernhard-42/three-cad-viewer#21] opened 2024-10-15 06:12 UTC
Hi, I noticed that the format in your example is like this and I was wondering how can I convert this format to allow me to preview any 3d cad drawing
![111](https://github.com/user-attachments/assets/4f70b7db-6636-4789-a07f-099c55cc48fb)

**Comment by bernhard-42** [comment] 2024-10-15 18:25
This is an internal format optimized for [VS Code Cad Viewer](https://github.com/bernhard-42/vscode-ocp-cad-viewer).
VS Code Cad Viewer is typically used with [CadQuery](https://github.com/CadQuery/cadquery) or [Build123d](https://github.com/gumyr/build123d). These Code-CAD packages allow to import CAD files like STEP and render with this javascript component in VS Code.

There are no plans to directly convert any CAD format to this format.

**Comment by bernhard-42** [comment] 2024-10-19 15:41
closing as a duplicate of [#17](https://github.com/bernhard-42/three-cad-viewer/issues/21)

**Closed by bernhard-42** 2024-10-19 15:41 UTC
Labels: duplicate, question
